require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "db/schema.rb"
    - "config/routes.rb"

convention:Rails/Output:
  Exclude:
    - "db/seeds.rb"

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Style/WordArray:
  Exclude:
    - "db/schema.rb"

Metrics/AbcSize:
  Exclude:
    - "app/finders/events_finder.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "app/finders/events_finder.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "app/finders/events_finder.rb"

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleMemoizedHelpers:
  Max: 20
