require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "db/schema.rb"
    - "config/routes.rb"

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Style/WordArray:
  Exclude:
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 20
